library(shiny)
library(shinydashboard)
library(leaflet)
library(dplyr)
library(plotly)
library(DT)
library(httr)
library(jsonlite)
library(ggplot2)
library(jsonlite)
library(DT)
library(ggplot2)
library(readr)
library(shinyWidgets)
library(leaflet.extras)
library(shinyjs)
library(tidyr)
library(RColorBrewer)
library(magrittr)

# Source code file
source("R/module_overview.R")
source("R/module_restaurants.R")
source("R/module_attractions.R")
source("R/module_accommodation.R")
source("R/module_transport.R")
source("R/module_weather.R")
source("R/module_data_sources.R")